### ISSUE TITLE
Question on Eqn (2) of the paper.

### ISSUE THREAD

**Issue by koow-eat** [naver-ai/DenseDiffusion#20]
Hi, 
Thanks for your inspiring work.
I have a question regarding the equation (2) of your paper:  
$M=\lambda_t\cdot R\odot M_{pos}\odot(1-S)-\lambda_t\cdot (1-R)\odot M_{neg}\odot(1-S)$,
In my opinion, $\lambda_t\cdot R\odot M_{pos}\odot(1-S)$ should be corrected to $\lambda_t\cdot R\odot M_{pos}\odot(S)$ so that
 the positive pair attention modification is confined to valid spatial regions (i.e., regions with binary mask valued as 1) not outside those regions. Could you correct me if I understood incorrectly?
Thanks

**Comment by YunjiKim** [comment]
Hi, @koow-eat .

I would like to first inform you that $S$ represents the area of the object to which each token belongs, and its purpose is to regulate the degree of adjustments so that it is disproportional to the size of the object.
Therefore, during the manipulation process, attention scores for token pairs (whether they are positive or negative) belonging to smaller objects are adjusted more than the ones belonging to larger objects.
It is actually $M_{pos}$ and $M_{neg}$ that notify which pairs are positive or negative, so I believe the equation is correct. 

I hope this comment resolves your inquiry. If you have any further questions, please feel free to ask!

**Comment by koow-eat** [comment]
Hi, 
Thank you for your reply.
But I'm still having trouble understanding this..

**1. Meaning of S**
For better clarity, let me denote $hw=|queries|$, where $hw$ is the height and width of the image.
Since $S\in\mathcal{R}^{hw\times |keys|}$, $S$ would be $|key|$ number of maps, but I'm not sure what are the values residing inside each map. It is stated that _"S is the segment area for each image query token."_ in the paper.  
So I assumed each value inside one of the maps indicates a value whether each query (i.e., image patch) and key belongs to the same segment. Is this correct? If then, how could this be related to your above statement, that $S$ controls the degree of adjustment, making the adjustment disproportional to the object's size?


**2. Meaning of $M_{neg}$ and $M_{neg}$**
Also, I understood $M_{pos}$ and $M_{neg}$ as the offset from each min/max query-key similarity. How could this be the indicator for positive/negative pairs?

**Comment by koow-eat** [comment]
It was my misunderstanding, my bad. It's a very interesting work.
