### ISSUE TITLE
How to obtain the map of the text mapping area

### ISSUE THREAD

**Issue by Asamoun** [naver-ai/DenseDiffusion#22]

**Comment by YunjiKim** [comment]
Hi, @Asamoun,

It would be easier to make layout guidance if you use the gradio app offered by this file (https://github.com/naver-ai/DenseDiffusion/blob/main/gradio_app.py).

Otherwise, if you use the code from this file (https://github.com/naver-ai/DenseDiffusion/blob/main/inference.ipynb), you need to create a new layout image in 'png' format with any programs you're comfortable with. Then, in the block 6 of this code, you also need to offer object-wise descriptions in order from largest to smallest. I recommend referring to the code.

**Comment by Asamoun** [comment]
thank you
